// ==========================================================================
// PAGE P.ORC1 — L'ORACLE (Operator)
// ==========================================================================
// Full-screen immersive HTML presentation of the brand strategy.
// Uses an iframe to render the self-contained HTML generated by
// html-presentation-generator.ts, with a top toolbar for actions.
// ==========================================================================

"use client";

import { use, useState, useRef, useCallback } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  Download,
  ExternalLink,
  Loader2,
  Maximize2,
  Minimize2,
  Eye,
  RefreshCw,
  AlertTriangle,
} from "lucide-react";

import { Button } from "~/components/ui/button";
import { Badge } from "~/components/ui/badge";

// ---------------------------------------------------------------------------
// Oracle Page — Operator
// ---------------------------------------------------------------------------

export default function OraclePage(props: {
  params: Promise<{ id: string }>;
}) {
  const params = use(props.params);
  const strategyId = params.id;
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);

  // Build the preview URL (POST endpoint rendered inline)
  const previewUrl = `/api/export/html/preview`;

  // ---------------------------------------------------------------------------
  // Load the HTML presentation into the iframe via POST
  // ---------------------------------------------------------------------------
  const loadPresentation = useCallback(
    async (iframe: HTMLIFrameElement) => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(previewUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ strategyId }),
        });

        if (!res.ok) {
          const errBody = await res.json().catch(() => ({}));
          throw new Error(
            (errBody as { error?: string }).error ??
              `Erreur ${res.status}`,
          );
        }

        const html = await res.text();

        // Write into the iframe
        const doc = iframe.contentDocument;
        if (doc) {
          doc.open();
          doc.write(html);
          doc.close();
        }
      } catch (err) {
        setError(
          err instanceof Error
            ? err.message
            : "Erreur lors du chargement de L'ORACLE",
        );
      } finally {
        setLoading(false);
      }
    },
    [previewUrl, strategyId],
  );

  // Ref callback — triggers initial load
  const iframeRefCallback = useCallback(
    (node: HTMLIFrameElement | null) => {
      if (node) {
        (iframeRef as React.MutableRefObject<HTMLIFrameElement>).current = node;
        void loadPresentation(node);
      }
    },
    [loadPresentation],
  );

  // ---------------------------------------------------------------------------
  // Download handler
  // ---------------------------------------------------------------------------
  const handleDownload = async () => {
    try {
      const res = await fetch("/api/export/html", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ strategyId }),
      });

      if (!res.ok) throw new Error("Erreur lors du téléchargement");

      const blob = await res.blob();
      const disposition = res.headers.get("Content-Disposition") ?? "";
      const filenameMatch = disposition.match(/filename="?([^"]+)"?/);
      const filename = filenameMatch?.[1] ?? "ORACLE.html";

      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      setError("Erreur lors du téléchargement");
    }
  };

  // ---------------------------------------------------------------------------
  // Fullscreen toggle
  // ---------------------------------------------------------------------------
  const toggleFullscreen = () => {
    const container = document.getElementById("oracle-container");
    if (!container) return;

    if (!document.fullscreenElement) {
      void container.requestFullscreen();
      setIsFullscreen(true);
    } else {
      void document.exitFullscreen();
      setIsFullscreen(false);
    }
  };

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------
  return (
    <div
      id="oracle-container"
      className="flex h-screen flex-col bg-zinc-950"
    >
      {/* ── Top toolbar ── */}
      <div className="flex items-center justify-between border-b border-white/10 bg-zinc-950/95 px-4 py-2.5">
        <div className="flex items-center gap-3">
          <Link
            href={`/impulsion/brand/${strategyId}`}
            className="flex items-center gap-1.5 text-sm text-white/60 hover:text-white transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span className="hidden sm:inline">Cockpit</span>
          </Link>
          <div className="h-4 w-px bg-white/10" />
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-emerald-500 to-violet-500">
              <Eye className="h-3.5 w-3.5 text-white" />
            </div>
            <div>
              <h1 className="text-sm font-bold text-white tracking-tight">
                L&apos;ORACLE
              </h1>
              <p className="text-[10px] uppercase tracking-widest text-white/40">
                Intelligence Stratégique
              </p>
            </div>
          </div>
          <Badge className="ml-2 bg-emerald-500/15 text-emerald-500 border-emerald-500/20 text-[10px] font-semibold uppercase tracking-wider">
            Interactif
          </Badge>
        </div>

        <div className="flex items-center gap-1.5">
          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5 text-white/60 hover:text-white hover:bg-white/5"
            onClick={() => {
              if (iframeRef.current) void loadPresentation(iframeRef.current);
            }}
          >
            <RefreshCw className="h-3.5 w-3.5" />
            <span className="hidden sm:inline text-xs">Rafraîchir</span>
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5 text-white/60 hover:text-white hover:bg-white/5"
            onClick={() => void handleDownload()}
          >
            <Download className="h-3.5 w-3.5" />
            <span className="hidden sm:inline text-xs">Télécharger</span>
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5 text-white/60 hover:text-white hover:bg-white/5"
            onClick={() => {
              window.open(
                `/impulsion/brand/${strategyId}/oracle`,
                "_blank",
              );
            }}
          >
            <ExternalLink className="h-3.5 w-3.5" />
            <span className="hidden sm:inline text-xs">Nouvel onglet</span>
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="h-8 text-white/60 hover:text-white hover:bg-white/5"
            onClick={toggleFullscreen}
          >
            {isFullscreen ? (
              <Minimize2 className="h-3.5 w-3.5" />
            ) : (
              <Maximize2 className="h-3.5 w-3.5" />
            )}
          </Button>
        </div>
      </div>

      {/* ── Content area ── */}
      <div className="relative flex-1 overflow-hidden">
        {/* Loading overlay */}
        {loading && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-zinc-950">
            <div className="relative">
              <div className="absolute inset-0 animate-ping rounded-full bg-emerald-500/20" />
              <div className="relative flex h-16 w-16 items-center justify-center rounded-full bg-emerald-500/10 border border-emerald-500/20">
                <Loader2 className="h-7 w-7 animate-spin text-emerald-500" />
              </div>
            </div>
            <p className="mt-4 text-sm font-medium text-white/60">
              Génération de L&apos;ORACLE...
            </p>
            <p className="mt-1 text-xs text-white/30">
              Compilation des 8 piliers stratégiques
            </p>
          </div>
        )}

        {/* Error state */}
        {error && !loading && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-zinc-950">
            <AlertTriangle className="h-10 w-10 text-red-400/60" />
            <p className="mt-3 text-sm font-medium text-white/70">
              {error}
            </p>
            <Button
              variant="outline"
              size="sm"
              className="mt-4 border-white/10 text-white/60 hover:text-white hover:bg-white/5"
              onClick={() => {
                if (iframeRef.current)
                  void loadPresentation(iframeRef.current);
              }}
            >
              <RefreshCw className="mr-2 h-3.5 w-3.5" />
              Réessayer
            </Button>
          </div>
        )}

        {/* The iframe — renders the complete HTML presentation */}
        <iframe
          ref={iframeRefCallback}
          title="L'ORACLE — Intelligence Stratégique"
          className="h-full w-full border-0"
          sandbox="allow-scripts allow-same-origin"
          style={{
            opacity: loading || error ? 0 : 1,
            transition: "opacity 0.3s ease",
          }}
        />
      </div>
    </div>
  );
}
